openapi: 3.0.2
info:
    title: API for aksesspunktleverandører i DPI
    version: 1.0.0
    description: API for kommunikasjon mellom C1 og C2 i firehjørers akritektur for DPI
paths:
    /{version}/send:    
      post:
        summary: intitierer og laseter opp ny forsendelse til C2.
        parameters: 
            - in: path
              name: version            
              schema:
                type: string                               
                description: versjon av API
              required: true
        requestBody:          
          description: består av to deler,  digitalpostmelding og dokumentpakke          
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  forettningsmelding: 
                    type: string
                    format: base64
                    description: 'Digitalpost melding formatert som base64 encoded JWT'
                  dokumentpakke: 
                    type: string
                    format: binary
                    description: kryptert dokumentpakke. Formate på dokumentpakke følger ASiC                    
        responses: 
          200: 
            description: Mottatt OK av aksesspunktleverandør, og vil bli sendt videre til postkasse
          400: 
            description: valideringsfeil - fornuftig beskrivelse bør inkluderes
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem'
          401:
            description: Utløpt token
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem'
          403:
            description: Token mangler "dpi:send" scope, eller avsender har ikke gyldig avtale med aksesspunktleverandør.
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem'   
    /{version}/statuses/{id}:
      get:
        summary: henter liste med statuser gitt foreendelsesid
        parameters: 
            - in: path
              name: version            
              schema:
                type: string                               
                description: versjon av API
              required: true
            - in: path
              name: id            
              schema: 
                type: string
                format: uuid
                description: unik id til meldingen
              required: true
        responses:
          200:
            description: liste med statuser  
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/statuses'          
          401:
            description: Utløpt token
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem'
          403:
            description: Token mangler "dpi:read" scope, eller avsender har ikke gyldig avtale med aksesspunktleverandør. 
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem'
    /{version}/getmessages:
      get: 
        summary: Henter ned liste med forettningsmeldinger på mottatte forsendelser
        parameters:
          - in: path
            name: version            
            schema:
              type: string                               
              description: versjon av API
            required: true
          - in: query
            name: mottakeridentifikator            
            schema:
              type: string
              description: identifikator til gitt i avsenderidentifikator ved sending av melding          
        responses:
          200: 
            description: 'Liste med forsendleser TODO: bør vi ha noen form for låsing?'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/messages'
          204:
            description: Ingen nye meldinger
          401:
            description: Utløpt token
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem'
          403:
            description: Token mangler "dpi:read" scope, eller avsender har ikke gyldig avtale med aksesspunktleverandør.
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem' 
          
    /{version}/downloadmessage/{id}:
      get:  
        summary: Laster ned dokumentpakke (ASiC) for gitt forsendelse
        parameters:
          - in: path
            name: version            
            schema:
              type: string                               
              description: versjon av API
            required: true
          - in: path
            name: id
            schema: 
              type: string
              format: uuid
              description: unik id til meldingen
            required: true
        responses:
          200:
            description: Kryptert dokumentpakke
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/dokumentpakke'
          401:
            description: Utløpt token
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem'
          403:
            description: Token mangler "dpi:read" scope, eller avsender har ikke gyldig avtale med aksesspunktleverandør.
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem' 
          404:
            description: Ugyldig id
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem'
    /{version}/setmessageread/{id}:
      post:
        summary: Setter forsendelse mottatt ovenfor aksesspunkt. Medfører at den blir fjernet fra listen hentnyeforsendelser returnerer. Aksesspunkt kan slette melding 
        parameters:
          - in: path
            name: version            
            schema:
              type: string                               
              description: versjon av API
            required: true
          - in: path
            name: id
            schema:
              type: string
              format: uuid
            required: true
        responses:
          200:
            description: Setter gitt forsendelse mottatt
          401:
            description: Utløpt token
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem'
          403:
            description: Token mangler "dpi:read" scope, eller avsender har ikke gyldig avtale med aksesspunktleverandør. 
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem'
          404:
            description: Ugyldig id
            content:
              application/problem+json:
                schema: 
                  $ref : '#/components/schemas/problem'
security:
  - OAuth2Schema:
    - dpi:send       
    - dpi:read
components:
  securitySchemes:
    OAuth2Schema:
      type: oauth2
      description: 'TODO: skal vi ha både read og write scope; Sett riktig url; Skriv skikkelig beskrivelse her'
      flows: 
        implicit:
          authorizationUrl: https://maskinporten.no/
          scopes: 
            'dpi:write' : for sending av meldinger
            'dpi:read' : for leseopperasjoner  
  schemas: 
    statuses:
      type: array
      items: 
        $ref: '#/components/schemas/status'
      uniqueItems: true
    status:
      type: object
      properties:
        status:
          type: string
          enum:
            - OPPRETTET
            - SENDT
            - MOTTATT
        timestamp:
          type: string
          format: date-time
    messages:
      type: array
      description: Liste med SBD (JWK, base64 formatert)
      items:
        $ref: '#/components/schemas/message'
    message:
      type: object  
      properties:
        forettningsmelding:
          type: string
          format: byte
          description: base64 formatert jwt som inneholder forettnignsmelding
        downloadurl:
          type: string
          format: uri
          description: uri meldingen kan lastes ned fra
    dokumentpakke:
      type: string
      format: binary  
    problem:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            Kopiert fra https://opensource.zalando.com/problem/schema.yaml#/Problem - Bør lage tilsvarende Digdir problem
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: 'about:blank'
          example: 'https://zalando.github.io/problem/constraint-violation'
        title:
          type: string
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.


